=== danielkupco/XWS-2015/WEB-INF/scheme/Faktura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xws/tim7/faktura"
    elementFormDefault="qualified" xmlns:fak="http://xws/tim7/faktura"
    xmlns:glob="http://xws/tim7/globals">

    <xs:import namespace="http://xws/tim7/globals" schemaLocation="Globals.xsd"/>

    <xs:element name="Faktura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Zaglavlje">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ID_poruke" type="glob:TIDPoruke"> </xs:element>
                            <xs:element name="Kupac" type="fak:TFirma"> </xs:element>
                            <xs:element name="Dobavljac" type="fak:TFirma"/>
                            <xs:element name="Broj_racuna">
                                <xs:simpleType>
                                    <xs:restriction base="xs:positiveInteger">
                                        <xs:totalDigits value="6"/>
                                        <xs:minInclusive value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Datum_racuna" type="xs:date"/>
                            <xs:element name="Vrednost_robe" type="glob:TDecimal15_2"> </xs:element>
                            <xs:element name="Vrednost_usluga" type="glob:TDecimal15_2"> </xs:element>
                            <xs:element name="Ukupno_roba_i_usluge" type="glob:TDecimal15_2"> </xs:element>
                            <xs:element name="Ukupan_rabat" type="glob:TDecimal15_2"> </xs:element>
                            <xs:element name="Ukupan_porez" type="glob:TDecimal15_2"> </xs:element>
                            <xs:element name="Oznaka_valute" type="glob:TOznakaValute"> </xs:element>
                            <xs:element name="Iznos_za_uplatu" type="glob:TDecimal15_2"> </xs:element>
                            <xs:element name="Uplata_na_racun" type="glob:TBrojRacuna"> </xs:element>
                            <xs:element name="Datum_valute" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" ref="fak:Stavka"> </xs:element>
                </xs:sequence>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Stavka">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Redni_broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:positiveInteger">
                            <xs:totalDigits value="3"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Naziv_robe_ili_usluge">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:length value="120"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Kolicina">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="10"/>
                            <xs:fractionDigits value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Jedinica_mere">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="6"/>
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Jedinicna_cena">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="10"/>
                            <xs:fractionDigits value="2"/>
                            <xs:minInclusive value="0"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Vrednost">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="12"/>
                            <xs:fractionDigits value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Procenat_rabata">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="5"/>
                            <xs:fractionDigits value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Iznos_rabata">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="12"/>
                            <xs:fractionDigits value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Umanjeno_za_rabat">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="12"/>
                            <xs:fractionDigits value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Ukupan_porez">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="12"/>
                            <xs:fractionDigits value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TFirma">
        <xs:sequence>
            <xs:element name="Naziv">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="255"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Adresa">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="255"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="PIB">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="11"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== danielkupco/XWS-2015/XWS-SOAP/initData/faktura2.xml
<?xml version="1.0" encoding="UTF-8"?>
<fak:Faktura xmlns:fak="http://xws/tim7/faktura"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://xws/tim7/faktura Faktura.xsd" id="123">
    <fak:Zaglavlje>
        <fak:ID_poruke>456</fak:ID_poruke>
        <fak:Kupac>
            <fak:Naziv>Firma 1</fak:Naziv>
            <fak:Adresa>Adresa firme 1</fak:Adresa>
            <fak:PIB>11111222223</fak:PIB>
        </fak:Kupac>
        <fak:Dobavljac>
            <fak:Naziv>Firma 2</fak:Naziv>
            <fak:Adresa>Adresa firme 2</fak:Adresa>
            <fak:PIB>44444555556</fak:PIB>
        </fak:Dobavljac>
        <fak:Broj_racuna>172929</fak:Broj_racuna>
        <fak:Datum_racuna>2015-09-22</fak:Datum_racuna>
        <fak:Vrednost_robe>1500.00</fak:Vrednost_robe>
        <fak:Vrednost_usluga>1200.99</fak:Vrednost_usluga>
        <fak:Ukupno_roba_i_usluge>2700.99</fak:Ukupno_roba_i_usluge>
        <fak:Ukupan_rabat>110.00</fak:Ukupan_rabat>
        <fak:Ukupan_porez>555.55</fak:Ukupan_porez>
        <fak:Oznaka_valute>RSD</fak:Oznaka_valute>
        <fak:Iznos_za_uplatu>3145.54</fak:Iznos_za_uplatu>
        <fak:Uplata_na_racun>444-5555555555555-66</fak:Uplata_na_racun>
        <fak:Datum_valute>2015-09-22</fak:Datum_valute>
    </fak:Zaglavlje>
    <fak:Stavka>
        <fak:Redni_broj>1</fak:Redni_broj>
        <fak:Naziv_robe_ili_usluge>Breskve</fak:Naziv_robe_ili_usluge>
        <fak:Kolicina>2</fak:Kolicina>
        <fak:Jedinica_mere>kg</fak:Jedinica_mere>
        <fak:Jedinicna_cena>330.20</fak:Jedinicna_cena>
        <fak:Vrednost>660.40</fak:Vrednost>
        <fak:Procenat_rabata>2.00</fak:Procenat_rabata>
        <fak:Iznos_rabata>16.00</fak:Iznos_rabata>
        <fak:Umanjeno_za_rabat>644.40</fak:Umanjeno_za_rabat>
        <fak:Ukupan_porez>36.00</fak:Ukupan_porez>
    </fak:Stavka>
    <fak:Stavka>
        <fak:Redni_broj>2</fak:Redni_broj>
        <fak:Naziv_robe_ili_usluge>Kajsije</fak:Naziv_robe_ili_usluge>
        <fak:Kolicina>3</fak:Kolicina>
        <fak:Jedinica_mere>kg</fak:Jedinica_mere>
        <fak:Jedinicna_cena>330.20</fak:Jedinicna_cena>
        <fak:Vrednost>660.40</fak:Vrednost>
        <fak:Procenat_rabata>2.00</fak:Procenat_rabata>
        <fak:Iznos_rabata>16.00</fak:Iznos_rabata>
        <fak:Umanjeno_za_rabat>644.40</fak:Umanjeno_za_rabat>
        <fak:Ukupan_porez>36.00</fak:Ukupan_porez>
    </fak:Stavka>
    <fak:Stavka>
        <fak:Redni_broj>3</fak:Redni_broj>
        <fak:Naziv_robe_ili_usluge>Sljive</fak:Naziv_robe_ili_usluge>
        <fak:Kolicina>3</fak:Kolicina>
        <fak:Jedinica_mere>kg</fak:Jedinica_mere>
        <fak:Jedinicna_cena>245.45</fak:Jedinicna_cena>
        <fak:Vrednost>736.35</fak:Vrednost>
        <fak:Procenat_rabata>3.15</fak:Procenat_rabata>
        <fak:Iznos_rabata>106.00</fak:Iznos_rabata>
        <fak:Umanjeno_za_rabat>730.00</fak:Umanjeno_za_rabat>
        <fak:Ukupan_porez>121.23</fak:Ukupan_porez>
    </fak:Stavka>
</fak:Faktura>
